name: Spielplan aus ICS-Dateien generieren

on:
  workflow_dispatch:
  schedule:
      - cron: "0 3 * * *"

jobs:
  build-from-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: pip install icalendar

      - name: HTML aus lokalen ICS-Dateien erzeugen
        run: python generate_from_files.py

      - name: HTML automatisch committen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "♻ HTML aus lokalen ICS-Dateien aktualisiert"
